name: print-name
on:
  push:

jobs:
  print-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Hello from the print-name workflow!"

